FROM confluentinc/cp-kafka-connect:latest

#If you want to run a private build uncomment the COPY command and make sure the JAR file is in the directory path
COPY mongo-kafka-connect-1.3.0-20200817.151244-6-all.jar /usr/share/confluent-hub-components

# If you want to run the latest production release of the connector, uncomment the following:
# RUN confluent-hub install --no-prompt mongodb/kafka-connect-mongodb:latest

ENV CONNECT_PLUGIN_PATH="/usr/share/java,/usr/share/confluent-hub-components"

RUN confluent-hub install --no-prompt debezium/debezium-connector-mysql:latest

